services:
    multilanguagesupport.model:
            class:        BiberLtd\Bundle\MultiLanguageSupportBundle\Services\MultiLanguageSupportModel
            arguments:    [@kernel, "default", "doctrine"]