services:
    multilanguagesupport.model:
            class:        BiberLtd\Core\Bundles\MultiLanguageSupportBundle\Services\MultiLanguageSupportModel
            arguments:    [@kernel, "default", "doctrine"]